import { BarChart3, UsersRound, Workflow } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useAnalytics } from "./hooks/useAnalytics";
import type { AnalyticsModule, Cohort, EntityKey, FlowCell } from "./types";
import type { AnalyticsOverlay, InsightGrid } from "../renderer/MapRenderer";

const entityLabels: Record<EntityKey, string> = { humans: "Human players", bots: "Bot players", loot: "Loot", pvpKills: "PvP kills", botKills: "Bot kills", playerDeaths: "Player deaths", stormDeaths: "Storm deaths" };
const entityColors: Record<EntityKey, string> = { humans: "#31d7e8", bots: "#f6b24d", loot: "#ffd166", pvpKills: "#ff5d6c", botKills: "#ef7b64", playerDeaths: "#ff9b4a", stormDeaths: "#b276ff" };
export function AnalyticsWorkbench({ mapId, cohort, onCohort, onOverlays, onFlowCell }: { mapId: string; cohort: Cohort; onCohort: (cohort: Cohort) => void; onOverlays: (overlays: readonly AnalyticsOverlay[]) => void; onFlowCell: (cell: InsightGrid | null) => void }) {
  const [module, setModule] = useState<AnalyticsModule>("entities"); const analytics = useAnalytics();
  return <section className="workbench" aria-label="Analytics Workbench"><div className="section-heading"><BarChart3 size={15} /><h2>Analytics Workbench - cumulative data across all matches</h2></div><div className="workbench-tabs">{([ ["entities", "Distribution", UsersRound], ["cohorts", "Cohorts", UsersRound], ["flow", "Flow", Workflow] ] as const).map(([id, label, Icon]) => <button key={id} className={module === id ? "active" : ""} onClick={() => { setModule(id); if (id !== "entities") onOverlays([]); }}><Icon size={13}/>{label}</button>)}</div>{analytics.status === "loading" && <p className="workbench-note">Loading aggregate telemetry...</p>}{analytics.status === "error" && <p className="workbench-note">Analytics artifacts are unavailable. Run preprocessing to rebuild them.</p>}{analytics.data && (module === "entities" ? <Entities mapId={mapId} data={analytics.data.entities} onOverlays={onOverlays} /> : module === "cohorts" ? <Cohorts cohort={cohort} onCohort={onCohort} data={analytics.data.cohorts} /> : <Flow mapId={mapId} data={analytics.data.flow} onCell={onFlowCell} />)}</section>;
}
function Entities({ mapId, data, onOverlays }: { mapId: string; data: import("./types").EntityDistribution; onOverlays: (overlays: readonly AnalyticsOverlay[]) => void }) { const [enabled, setEnabled] = useState<EntityKey[]>(["humans", "bots", "loot"]); const [opacity, setOpacity] = useState(.58); const map = data.maps[mapId]; useEffect(() => { onOverlays(map ? enabled.map(key => ({ columns: data.gridSize, rows: data.gridSize, values: map.grids[key], color: entityColors[key], opacity })) : []); }, [map, enabled, opacity, data.gridSize, onOverlays]); if (!map) return <p className="workbench-note">Choose a map to inspect aggregate distribution.</p>; return <><p className="workbench-note">Compare source layers; counts aggregate all available matches.</p><label className="field">Overlay opacity<input type="range" min="0.1" max="1" step=".05" value={opacity} onChange={event => setOpacity(Number(event.target.value))}/></label><div className="overlay-list">{(Object.keys(entityLabels) as EntityKey[]).map((key) => <label key={key}><input type="checkbox" checked={enabled.includes(key)} onChange={() => setEnabled(current => current.includes(key) ? current.filter(item => item !== key) : [...current, key])}/><i style={{ background: entityColors[key] }}/><span>{entityLabels[key]}</span><b>{map.counters[key] ?? 0}</b></label>)}</div><dl className="analytics-stats"><Metric label="Human / bot" value={format(map.counters.humanBotRatio)} /><Metric label="PvP / PvE" value={format(map.counters.pvpPveRatio)} /><Metric label="Selected layers" value={String(enabled.length)} /><Metric label="Grid resolution" value={`${data.gridSize} x ${data.gridSize}`} /></dl></> }
function Cohorts({ cohort, onCohort, data }: { cohort: Cohort; onCohort: (value: Cohort) => void; data: import("./types").PlayerCohorts }) { const players = data.players.filter(player => cohort === "all" || player.cohort === cohort); const sessions = players.flatMap(player => player.sessions); const top = [...players].sort((a,b) => b.matchCount-a.matchCount).slice(0,3); return <><select aria-label="Player cohort" value={cohort} onChange={event => onCohort(event.target.value as Cohort)}>{[["all","All players"],["firstSession","First session"],["returning","Returning"],["frequent","Frequent"]].map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select><dl className="analytics-stats"><Metric label="Players" value={String(players.length)} /><Metric label="Avg matches" value={format(players.length ? sessions.length / players.length : 0)} /><Metric label="Avg survival" value={`${format(sessions.length ? sessions.reduce((sum, item) => sum + item.survivalTime, 0) / sessions.length : 0)}s`} /><Metric label="Events / min" value={format(sessions.reduce((sum, item) => sum + item.eventCount, 0) / Math.max(1, sessions.reduce((sum, item) => sum + item.survivalTime, 0) / 60))} /></dl><p className="mini-title">Daily active players</p><div className="day-bars">{data.daily.map(day => <span key={day.date} title={`${day.date}: ${day.active} active`} style={{ height: `${Math.max(4, day.active / Math.max(...data.daily.map(item => item.active)) * 34)}px` }} />)}</div><p className="mini-title">Top returning players</p>{top.map(player => <p className="rank-line" key={player.id}><code>{player.id.slice(0,8)}</code><b>{player.matchCount} matches</b></p>)}</> }
function Flow({ mapId, data, onCell }: { mapId: string; data: import("./types").FlowAnalysis; onCell: (grid: InsightGrid | null) => void }) { const [mode, setMode] = useState<"absolute"|"normalized">("absolute"); const [sort, setSort] = useState<keyof FlowCell>("traffic"); const cells = data.maps[mapId]?.cells ?? []; const ranked = useMemo(() => [...cells].sort((a,b) => metric(b,sort,mode)-metric(a,sort,mode)).slice(0,5), [cells,sort,mode]); return <><div className="segmented"><button className={mode === "absolute" ? "active" : ""} onClick={() => setMode("absolute")}>Absolute</button><button className={mode === "normalized" ? "active" : ""} onClick={() => setMode("normalized")}>Normalized</button></div><select aria-label="Flow ranking" value={sort} onChange={event => setSort(event.target.value as keyof FlowCell)}>{[["traffic","Highest traffic"],["loot","Highest loot"],["botKills","Highest combat"],["playerDeaths","Highest death rate"],["pvpKills","Highest PvP"]].map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select><p className="workbench-note">Normalized values are events per recorded visit. Select a ranked cell to inspect its map grid location.</p><div className="ranking">{ranked.map((cell,index) => <button key={cell.id} onClick={() => onCell({ column: cell.id % data.gridSize, row: Math.floor(cell.id/data.gridSize), divisions: data.gridSize })}><span>#{index+1} Cell {cell.id % data.gridSize + 1},{Math.floor(cell.id/data.gridSize)+1}</span><b>{format(metric(cell,sort,mode))}</b><small>{cell.traffic} visits · {cell.botEncounters} bot encounters</small></button>)}</div></> }
function metric(cell: FlowCell, key: keyof FlowCell, mode: "absolute"|"normalized"): number { const raw = typeof cell[key] === "number" ? cell[key] : 0; return mode === "normalized" && key !== "traffic" ? raw / Math.max(1, cell.traffic) : raw; }
function Metric({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div> } function format(value: number | null | undefined): string { return value === null || value === undefined ? "--" : value.toFixed(value >= 10 ? 0 : 2); }
